# Generated by Django 4.2.2 on 2023-07-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
