# Generated by Django 4.2.2 on 2023-07-19 05:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('caption', models.CharField(max_length=250, null=True)),
                ('files', models.FileField(upload_to='images/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.userprofile')),
            ],
        ),
    ]
