# Generated by Django 4.2.2 on 2023-07-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_userprofile_profile_image_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='social.userprofile'),
        ),
    ]
