# Generated by Django 4.2.2 on 2023-08-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
    ]
