# Generated by Django 4.2.2 on 2023-08-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female')], default=1),
        ),
    ]
