# Generated by Django 4.2.5 on 2023-12-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='files',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
