# Generated by Django 4.2.3 on 2023-08-10 05:34

from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.IntegerField(db_index=True, default=121)),
                ('updated_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.IntegerField(db_index=True, default=121)),
                ('updated_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('client_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=1000)),
                ('type', models.IntegerField(choices=[(1, 'Svg'), (2, 'Image')], default=1)),
                ('html', models.TextField(blank=True, help_text='\n            It Will have the child tags of \'svg\' HTML tag because color (fill), \n            height, and width properties will be variable that is why we need \n            to store only the child tags of <svg>, like below:, like:\n              <!-- <svg id="icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"> -->\n                <defs>\n                  <style>\n                    .cls-1 {\n                      fill: none;\n                    }\n                  </style>\n                </defs>\n                <path d="M22.9961,30H9.0039a1.0022,1.0022,0,0,1-.821-1.5769l6.9977-9.9965a1,1,0,0,1,1.6388,0l6.9977,9.9965A1.0022,1.0022,0,0,1,22.9961,30ZM10.92,28H21.08L16,20.7439Z"/>\n                <path d="M28,24H24V22h4V6H4V22H8v2H4a2.0021,2.0021,0,0,1-2-2V6A2.0021,2.0021,0,0,1,4,4H28a2.0021,2.0021,0,0,1,2,2V22A2.0021,2.0021,0,0,1,28,24Z"/>\n                <rect id="_Transparent_Rectangle_" data-name="&lt;Transparent Rectangle&gt;" class="cls-1" width="32" height="32"/>\n              <!-- </svg> -->\n            ', null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=social.models.Icon.icon_upload_to)),
                ('url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.category')),
            ],
            options={
                'unique_together': {('category', 'client_id', 'name', 'type')},
            },
        ),
    ]
