# Generated by Django 4.2.3 on 2023-08-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='html',
            field=models.TextField(blank=True, help_text=(), null=True),
        ),
    ]
