# Generated by Django 4.2.3 on 2023-08-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_alter_icon_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='internal_name',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='internal_name',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
